### PR TITLE
Considering key order while adding a new row. Fix for issue #106 

### PR DESCRIPTION
**Pull request by Joshua-Dias-Barreto**
Added addRowWithColumnNamesAsKeys and addRowWithColumnNamesAsKeysAtPosition along with tests.
These methods consider the key order while adding a new row.
The keys of the Data Series correspond to the column names.

### CODE REVIEW

**Comment by olekscode** [comment]
I think that this should be the behavior by default when we add a DataSeries as row.
So the names of those methods should simply be `addRow:` and `addRow:atPosition:`

**Comment by jecisc** [comment]
I agree with Oleks

**Comment by Joshua-Dias-Barreto** [comment]
> I think that this should be the behavior by default when we add a DataSeries as row. So the names of those methods should simply be `addRow:` and `addRow:atPosition:`

I've now made the changes to `addRow:` and `addRow:atPosition:` itself. The methods first check whether the keys of the data series are SmallIntegers, if they are then `addRow:` and `addRow:atPosition:` methods work just the way they worked before. But if they are not SmallIntegers, it indicates that the keys of the data series are intended to be the column names of the DataFrame.

**Comment by olekscode** [comment]
@Joshua-Dias-Barreto could you please submit the comments that you added to the stats methods as a separate PR? Those comments are good and I can accept the PR right away

For the other methods, I have some feedback to share with you

**Comment by Joshua-Dias-Barreto** [comment]
@olekscode sure, I've created another PR now just for the comments

**Pull request closed without merging**
