### PR TITLE
Added describe method for numeric dataframes

### PR DESCRIPTION
**Pull request by Joshua-Dias-Barreto**
This method is similar to [pandas.describe()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) and it will be useful in providing a statistic description of the dataframe.
Tests are also written for this method.
This fixes issue #167

### CODE REVIEW

**Comment by olekscode** [comment]
Based on my comments, I would rewrite this method in the following way:

```st
DataFrame >> describe
    "Answer another data frame with statistics describing the columns of this data frame"
    
    | numericalColumns numericalColumnNames contents |

    numericalColumns := self columns
        "TODO: Remove this line when columns returns a collection of series"
        collect: [ :column | column asDataSeries ]
        thenSelect: [ :column | column isNumerical ].
        
    "TODO: Rewrite this when columns returns a collection of series"
    numericalColumnNames := self columnNames select: [ :name |
        (data column: name) isNumerical ].

    contents := numericalColumns collect: [ :column |
        {     
            column size .
            column average .
            column stdev .
            column min .
            column firstQuartile .
            column secondQuartile .
            column thirdQuartile .
            column max .
            column calculateDataType
        } ].

    ^ DataFrame 
        withRows: contents
        rowNames: numericalColumnNames
        columnNames: #(count mean std min '25%' '50%' '75%' max dtype).
```

**Comment by olekscode** [comment]
It also suggest three more issues:

1. `DataFrame >> columns` should return a collection of series and not a collection of arrays. Each series should remember the column name

2. Maybe also add a method `DataFrame >> numericalColumns` that will simply return `self columns select: [ :column | column isNumerical ]` and also `DataFrame >> numericalColumnNames` that would return `self numericalColumns collect: [ :column | column name ]`

3. Make sure that statistical methods (`average`, `stdev`, etc.) can handle `nil` values. For example, `#(2 nil 3 1 4) asDataSeries average` should return `2.5`

If that is done, we can rewrite the `describe` method like this:

```st
DataFrame >> describe
    "Answer another data frame with statistics describing the columns of this data frame"
    
    | contents |

    contents := self numericalColumns collect: [ :column |    
        {     
            column countNonNils .
            column average .
            column stdev .
            column min .
            column firstQuartile .
            column secondQuartile .
            column thirdQuartile .
            column max .
            column calculateDataType
        } ].

    ^ DataFrame 
        withRows: contents
        rowNames: self numericalColumnNames
        columnNames: #(count mean std min '25%' '50%' '75%' max dtype).
```

**Review by jecisc — CHANGES_REQUESTED** [review]
I gave some comments on the general way to code in smalltalk but the change proposed by Oleks seems good.

I think we can optimize it further but it is better to treat that later.

**Comment by jecisc** [comment]
> It also suggest three more issues:
> 
>     1. `DataFrame >> columns` should return a collection of series and not a collection of arrays. Each series should remember the column name
> 

Yes! but the implementation of #columns should be kept in #arrayOfColumns and most users should use this one. The reason is that I optimized #columns a while ago because it's a method that can be long on big dataframe and a lot of things were slow because of that. So, when it's not necessary to have a DataSeries instead of an Array, we should use an Array because creating a DataSeries takes more time.

>     2. Maybe also add a method `DataFrame >> numericalColumns` that will simply return `self columns select: [ :column | column isNumerical ]` and also `DataFrame >> numericalColumnNames` that would return `self numericalColumns collect: [ :column | column name ]`
> 

I was gonna propose that but I think there is a way faster way using: `((self dataTypes at: column) includesBehavior: Number)`. Because DataSeries>>isNumerical will scan the full DataSeries.

>     3. Make sure that statistical methods (`average`, `stdev`, etc.) can handle `nil` values. For example, `#(2 nil 3 1 4) asDataSeries average` should return `2.5`
> 

I think I already opened an issue about that? If I didn't it's just that I forgot :( 
I already managed the nils in #average IIRC

> 
> If that is done, we can rewrite the `describe` method like this:
> 
> ```smalltalk
> DataFrame >> describe
>     "Answer another data frame with statistics describing the columns of this data frame"
>     
>     | contents |
> 
>     contents := self numericalColumns collect: [ :column |    
>         {     
>             column countNonNils .
>             column average .
>             column stdev .
>             column min .
>             column firstQuartile .
>             column secondQuartile .
>             column thirdQuartile .
>             column max .
>             column calculateDataType
>         } ].
> 
>     ^ DataFrame 
>         withRows: contents
>         rowNames: self numericalColumnNames
>         columnNames: #(count mean std min '25%' '50%' '75%' max dtype).
> ```

**Comment by jecisc** [comment]
#columns should return a collection of DataSeries 
#arrayOfColumns should return an array of array 

I though we have a method named #rows but apparently we do not, sorry for the confusion.

For #columns we could have a simple implementation for a start that is:

```st
    self ifEmpty: [ ^ #() ].

    ^ self columnsFrom: 1 to: self numberOfColumns
```

I don't know if in term of perf this would be the best, but we can do a first implementation with tests and iterate later if the perfs are not good on big data. 

If you want to do those changes I can propose you two ways:
- Either we integrate this PR with the version of the method given by Oleks here: https://github.com/PolyMathOrg/DataFrame/pull/226#issuecomment-1547390457. And after that we add the 3 missing features and update this method afterward
- Either you do one PR for each improvement/missing feature and once it's done you can merge master into your branch and update your PR

I would prefer that we do not tackle 4 issues in 1 PR.

**Comment by Joshua-Dias-Barreto** [comment]
Okay thanks, I think I will do one PR for each improvement/missing feature and then I will update this PR.

**Comment by Joshua-Dias-Barreto** [comment]
>For #columns we could have a simple implementation for a start that is:

    self ifEmpty: [ ^ #() ].

    ^ self columnsFrom: 1 to: self numberOfColumns


For some reason when I try to use `columns` after implementing it like this, my image crashes.

When I tried to implement it like this:

    ^ self columnsFrom: 1 to: self numberOfColumns

It gives an out of bounds error, even if the number of columns is greater than 1.

And is there any difference between just `^ self` and `^ self columnsFrom: 1 to: self numberOfColumns`

**Comment by jecisc** [comment]
`^ self` will return the current instance (self). If there is no return in the method, this is what is returned by default.

`^ self columnsFrom: 1 to: self numberOfColumns` will return the result of #columnsFrom:to:.

Do the image freeze when you save the method or when you run the tests?

If it's while running the tests: I think that what must happens is that doing this change impact the perfs a lot and some tests are taking a lot of time (because the methods using #columns currently should use #asArrayOfColumns that is much faster). And the image seems frozen because the tests are long (we have a time limit for the tests but it is 10sec by test by default)

**Comment by Joshua-Dias-Barreto** [comment]
It freezes when I run the tests and even if I try to use it in the playground image.

There is no issue while saving the method.

**Comment by Joshua-Dias-Barreto** [comment]
>2. Maybe also add a method `DataFrame >> numericalColumns` that will simply return `self columns select: [ :column | column isNumerical ]` and also `DataFrame >> numericalColumnNames` that would return `self numericalColumns collect: [ :column | column name ]`
I was gonna propose that but I think there is a way faster way using: ((self dataTypes at: column) includesBehavior: Number). Because DataSeries>>isNumerical will scan the full DataSeries.

DataFrame>> #dataTypes at: requires the column name, so maybe we can implement numericalColumns like this:

```
numericalColumns

	^ self columnNames select: [ :columnName |
		  (self dataTypes at: columnName) includesBehavior: Number ]
```

**Comment by Joshua-Dias-Barreto** [comment]
@jecisc could you let me know your thoughts regarding this implementation of `numericalColumns` and `numericalColumnNames`

```
numericalColumnNames

	^ self columnNames select: [ :columnName |
		  (self dataTypes at: columnName) includesBehavior: Number ]
```

```
numericalColumns

	^ self columns: self numericalColumnNames
```

We cannot use this directly for `numericalColumns`
>Maybe also add a method DataFrame >> numericalColumns that will simply return self columns select: [ :column | column isNumerical ] and also DataFrame >> numericalColumnNames that would return self numericalColumns collect: [ :column | column name ]
I was gonna propose that but I think there is a way faster way using: ((self dataTypes at: column) includesBehavior: Number). Because DataSeries>>isNumerical will scan the full DataSeries.

 because `dataTypesAt:` requires the column name

**Comment by jecisc** [comment]
Those two methods seems good to me!

**Comment by jecisc** [comment]
Since #numericalColumns should return an array, then there is no question of "row" or "columns" wise. It should be applied to all data series in the array. And in this case the data series should represent the columns.

**Pull request merged**
