### PR TITLE
Replace GT inspector by newtools-spec2 inspector

### LINKED ISSUE #148: Remove the methods that define a FastTable tab in GTInspector
This tab does not work anymore in the recent versions of Pharo.
We should have a Spec view for DataFrame now (see issue #147).

Methods to be removed are in the `gt-inspector-extension` protocol:

- `DataFrame >> gtInspectorFastTableIn:`
- `DataFrame >> gtInspectorItemsIn:`
- `DataFrame >> showWithGlamourIn:`

### PR DESCRIPTION
**Pull request by tinchodias**
Fixes #148

### CODE REVIEW

**Comment by tinchodias** [comment]
Tested manually with:
```
df := DataFrame 
	withRowNames: #(r1 r2)
	columnNames: #(c1 c2 c3 c4).

1 to: df rowNames size do: [ :rowIndex |
	1 to: df columnNames size do: [ :columnIndex |
		df 
			at: rowIndex at: columnIndex 
			put: (rowIndex asString, columnIndex asString) ] ].

df.
```

**Comment by tinchodias** [comment]
Which looks like  this in a recent Pharo 10:
Screen Shot 2021-11-26 at 18 29 08

**Comment by tinchodias** [comment]
But it has a problem: when user clicks on a row, the row index will be inspected on the right side... I guess it should inspect the "cell contents", right? But didn't check on other inspection* methods on the image to fix it.

**Comment by Ducasse** [comment]
Martin please ask esteban because this is really important to know how to decide what should flow.

S

**Comment by tinchodias** [comment]
Right, I asked and will come come back with news.

**Comment by Ducasse** [comment]
@martin what are the news because it would be good to be able to integrate with the new inspector

**Comment by jordanmontt** [comment]
Yes, it would be nice to merge this PR. Do you have any news @tinchodias ?

**Comment by tinchodias** [comment]
The automatic merge is wrong... To do it simple, I will create a new PR from another branch.

**Comment by tinchodias** [comment]
@jordanmontt @Ducasse it's fixed in #163

**Pull request closed without merging**
